## Series
#### It is like a coloumn / row in a table

In [2]:
import pandas as pd
marks = pd.Series([23,43,67,93,45,56])
print(marks)

0    23
1    43
2    67
3    93
4    45
5    56
dtype: int64

In [3]:
print(marks[2:6])

2    67
3    93
4    45
5    56
dtype: int64

In [4]:
marks = pd.Series([23,43,67,93,45,56], index = ['a','b','c','d','e','f'])
print(marks)

a    23
b    43
c    67
d    93
e    45
f    56
dtype: int64

## Data Frame

#### A dataframe is like a table --> have both row & coloumns

In [7]:
student = {
    'Marks' : [32,54,65,22],
    'Sub': ['A', 'B', 'C', 'D']
}

df = pd.DataFrame(student, index = [1,2,3,4])
print(df)

   Marks Sub
1     32   A
2     54   B
3     65   C
4     22   D

In [12]:
print(df.iloc[[1,3]])

   Marks Sub
2     54   B
4     22   D

In [13]:
print(df.loc[[1,3]])

   Marks Sub
1     32   A
3     65   C

#### How to read a file

In [16]:
df = pd.read_csv("..\Data\data.csv")
print(df.to_string())

   Id         Name  Country
0   1     Vanshika    India
1   2         John  America
2   3        Quang    Japan
3   4          Xhi    China
4   5  Lee Min Hoo    Korea

#### Top & Bottom Values

In [19]:
df = pd.read_csv("..\Data\data.csv")
df.head(2)

   Id      Name  Country
0   1  Vanshika    India
1   2      John  America

In [20]:
df = pd.read_csv("..\Data\data.csv")
df.tail(2)

   Id         Name Country
3   4          Xhi   China
4   5  Lee Min Hoo   Korea

#### Analysis Part (Step - 2 Cleaning)